"use client";

import { useEffect, useState } from "react";
import { builtinMealFoods } from "@/lib/data/meals";
import { mealCategories } from "@/lib/meals/constants";
import { defaultMealPersonalData, loadMealPersonalData, type MealPersonalData } from "@/lib/meals/storage";
import { defaultMilkTeaPersonalData, loadMilkTeaPersonalData } from "@/lib/milk-tea/storage";
import { defaultTakeoutPersonalData, loadTakeoutPersonalData, type TakeoutPersonalData } from "@/lib/takeout/storage";
import type { MilkTeaPersonalData } from "@/types/milk-tea";
import type { TakeoutReferenceItem } from "@/types/takeout";

export function DataOverview({ brandSummaries, milkStats, canteenStats, takeoutStats, takeoutCategories }: { brandSummaries: Array<{ name: string; products: number; variants: number; toppings: number }>; milkStats: { products: number; variants: number; toppings: number; detailed: number }; canteenStats: { canteens: number; servicePoints: number; physicalFloors: number; structuralFloorNodes: number; windows: number; dishes: number; skus: number; activities: number; windowPendingDishes: number }; takeoutStats: { merchants: number; categories: number; areas: number; evidenceA: number }; takeoutCategories: TakeoutReferenceItem[] }) {
  const [tab, setTab] = useState<"meals" | "canteens" | "takeout" | "milk">("meals");
  const [personal, setPersonal] = useState<MealPersonalData>(defaultMealPersonalData);
  const [milkPersonal, setMilkPersonal] = useState<MilkTeaPersonalData>(defaultMilkTeaPersonalData);
  const [takeoutPersonal, setTakeoutPersonal] = useState<TakeoutPersonalData>(defaultTakeoutPersonalData);
  useEffect(() => {
    const timer = window.setTimeout(() => {
      setPersonal(loadMealPersonalData().data);
      setMilkPersonal(loadMilkTeaPersonalData().data);
      setTakeoutPersonal(loadTakeoutPersonalData().data);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  return <main className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><header className="max-w-3xl"><p className="text-xs font-semibold tracking-[0.18em] text-[#176b55]">DATA OVERVIEW</p><h1 className="mt-3 font-serif text-4xl font-bold text-[#173f35] sm:text-5xl">四套选择，一处说明数据边界。</h1><p className="mt-5 text-base leading-8 text-stone-600">正餐、北大食堂、外卖和奶茶使用彼此独立的数据结构与本地存储。</p></header><div className="mt-10 inline-grid max-w-full grid-cols-2 rounded-2xl bg-stone-200/70 p-1 sm:grid-cols-4"><button type="button" aria-pressed={tab === "meals"} onClick={() => setTab("meals")} className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${tab === "meals" ? "bg-white text-[#173f35] shadow-sm" : "text-stone-500"}`}>食物选项</button><button type="button" aria-pressed={tab === "canteens"} onClick={() => setTab("canteens")} className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${tab === "canteens" ? "bg-white text-[#173f35] shadow-sm" : "text-stone-500"}`}>北大食堂</button><button type="button" aria-pressed={tab === "takeout"} onClick={() => setTab("takeout")} className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${tab === "takeout" ? "bg-white text-[#173f35] shadow-sm" : "text-stone-500"}`}>外卖数据</button><button type="button" aria-pressed={tab === "milk"} onClick={() => setTab("milk")} className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${tab === "milk" ? "bg-white text-[#173f35] shadow-sm" : "text-stone-500"}`}>奶茶数据</button></div>{tab === "meals" ? <MealStats personal={personal} /> : tab === "canteens" ? <CanteenStats stats={canteenStats} /> : tab === "takeout" ? <TakeoutStats stats={takeoutStats} categories={takeoutCategories} personal={takeoutPersonal} /> : <MilkStats summaries={brandSummaries} stats={milkStats} personal={milkPersonal} />}</main>;
}

function TakeoutStats({ stats, categories, personal }: { stats: { merchants: number; categories: number; areas: number; evidenceA: number }; categories: TakeoutReferenceItem[]; personal: TakeoutPersonalData }) { return <><section className="mt-10 grid grid-cols-2 gap-y-6 border-y border-stone-300 py-6 sm:grid-cols-4"><Stat value={stats.merchants} label="候选商户" /><Stat value={stats.categories} label="主分类" /><Stat value={stats.areas} label="覆盖商圈" /><Stat value={stats.evidenceA} label="A级证据" /></section><section className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <article key={category.id} className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs font-semibold tracking-[.14em] text-[#176b55]">{category.shortLabel}</p><h2 className="mt-2 font-serif text-2xl font-bold text-[#173f35]">{category.name}</h2><p className="mt-4 font-mono text-3xl font-bold text-stone-900">{category.merchantCount}</p></article>)}</section><p className="mt-8 text-sm leading-7 text-stone-500">个人数据：{personal.customMerchants.length} 家自定义、{personal.favorites.length} 项收藏、{personal.permanentExclusions.length} 项永久排除、{personal.history.length} 条最近记录。公开候选库未接入美团或饿了么，不能据此判断当前是否可送。</p></>; }

function CanteenStats({ stats }: { stats: { canteens: number; servicePoints: number; physicalFloors: number; windows: number; dishes: number; skus: number; activities: number; windowPendingDishes: number } }) { return <><section className="mt-10 grid grid-cols-2 gap-y-6 border-y border-stone-300 py-6 sm:grid-cols-4"><Stat value={stats.canteens - stats.servicePoints} label="正式食堂" /><Stat value={stats.physicalFloors} label="可靠物理楼层" /><Stat value={stats.windows} label="窗口/档口" /><Stat value={stats.dishes} label="结构化菜品" /></section><section className="mt-12 grid gap-5 sm:grid-cols-3"><article className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs text-stone-500">GitHub 历史 SKU</p><p className="mt-3 font-mono text-3xl font-bold text-[#173f35]">{stats.skus}</p></article><article className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs text-stone-500">窗口待确认菜品</p><p className="mt-3 font-mono text-3xl font-bold text-[#173f35]">{stats.windowPendingDishes}</p></article><article className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs text-stone-500">临时活动记录</p><p className="mt-3 font-mono text-3xl font-bold text-[#173f35]">{stats.activities}</p></article></section><p className="mt-8 text-sm leading-7 text-stone-500">历史价格和营养均不代表当前在售、现价或医学精确测量；窗口不明确的历史菜品不会根据名称自动绑定。</p></>; }

function MealStats({ personal }: { personal: MealPersonalData }) { const stats = [[builtinMealFoods.length, "内置食物"], [mealCategories.length, "主分类"], [personal.customFoods.length, "自定义"], [personal.history.length, "最近记录"]] as const; return <><section className="mt-10 grid grid-cols-2 gap-y-6 border-y border-stone-300 py-6 sm:grid-cols-4">{stats.map(([value, label]) => <Stat key={label} value={value} label={label} />)}</section><section className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{mealCategories.map((category) => <article key={category.id} className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs font-semibold tracking-[.14em] text-[#c96348]">{category.shortLabel}</p><h2 className="mt-2 font-serif text-2xl font-bold text-[#173f35]">{category.name}</h2><p className="mt-4 font-mono text-3xl font-bold text-stone-900">{category.count}</p></article>)}</section><p className="mt-8 text-sm leading-7 text-stone-500">另有 {personal.favorites.length} 项收藏、{personal.permanentlyExcluded.length} 项永久排除。价格、口味、时间和饱腹标签是一般化决策参考，不是官方门店数据。</p></>; }
function MilkStats({ summaries, stats, personal }: { summaries: Array<{ name: string; products: number; variants: number; toppings: number }>; stats: { products: number; variants: number; toppings: number; detailed: number }; personal: MilkTeaPersonalData }) { return <><section className="mt-10 grid grid-cols-2 gap-y-6 border-y border-stone-300 py-6 sm:grid-cols-4"><Stat value={stats.products} label="独立产品" /><Stat value={stats.variants} label="规格热量记录" /><Stat value={stats.toppings} label="独立小料" /><Stat value={stats.detailed} label="含精细规格产品" /></section><section className="mt-12 grid gap-5 sm:grid-cols-2">{summaries.map((brand) => <article key={brand.name} className="rounded-[1.75rem] border border-stone-200 bg-white p-6"><p className="text-xs font-semibold tracking-[.14em] text-[#176b55]">{brand.name}</p><p className="mt-3 font-serif text-3xl font-bold text-stone-900">{brand.products} 款</p><p className="mt-3 text-sm leading-6 text-stone-500">{brand.variants} 条规格热量记录 · {brand.toppings} 种独立小料</p></article>)}</section><p className="mt-8 text-sm leading-7 text-stone-500">个人数据：{personal.favorites.length} 项收藏、{personal.permanentlyExcluded.length} 项永久排除、{personal.history.length} 条最近记录。在线站与离线版分别保存在各自浏览器环境中。</p></>; }
function Stat({ value, label }: { value: number; label: string }) { return <div className="min-w-0 border-r border-stone-300 px-3 last:border-r-0 sm:px-6"><p className="break-words text-xs text-stone-500 sm:text-sm">{label}</p><p className="mt-3 font-mono text-2xl font-bold text-[#173f35] sm:text-4xl">{value}</p></div>; }
