    var MEAL_FOODS = __MEAL_DATA__;
    var MEAL_CATEGORIES = [{id:"rice",name:"米饭套餐",shortLabel:"米饭"},{id:"noodles",name:"面 / 粉",shortLabel:"面粉"},{id:"dumplings",name:"饺子包点",shortLabel:"饺子"},{id:"spicy_pot",name:"麻辣锅物",shortLabel:"麻辣"},{id:"chinese_snack",name:"中式小吃",shortLabel:"中式"},{id:"asia",name:"日韩东南亚",shortLabel:"亚洲"},{id:"western",name:"西式快餐",shortLabel:"西式"},{id:"light",name:"汤粥轻食",shortLabel:"轻食"},{id:"group",name:"聚餐烧烤",shortLabel:"聚餐"}];
    var MEAL_PRICE = {under15:"15 元以内","15_25":"15～25 元","25_40":"25～40 元","40_70":"40～70 元","70_plus":"70 元以上"};
    var MEAL_FLAVOR = {light:"清淡鲜香",savory:"咸香下饭",sour_spicy:"酸辣开胃",mala:"麻辣重口",sweet_sour:"酸甜",curry_sauce:"咖喱 / 酱香",fried_grilled:"烧烤 / 油炸"};
    var MEAL_TIME = {fast:"赶时间",normal:"正常吃",slow:"慢慢吃"};
    var MEAL_FULLNESS = {light:"轻一点",normal:"正常吃",heavy:"很顶饱"};
    var MEAL_SCENE = {solo:"一个人",small_group:"两三个人",group:"多人聚餐",dine_in:"堂食",delivery:"外卖",takeout:"打包带走"};
    var MEAL_EXCLUDE = {mala:"不吃辣",rice:"不想吃米饭",noodle:"不想吃面或粉",soup:"不想吃汤汤水水",fried:"不想吃油炸",pork:"不吃猪肉",beef_lamb:"不吃牛羊肉",seafood:"不吃海鲜",vegetarian_friendly:"素食优先"};
    var MEAL_KEYS = {custom:"foodCompass.meal.customFoods",favorites:"foodCompass.meal.favorites",excluded:"foodCompass.meal.permanentExclusions",history:"foodCompass.meal.history",settings:"foodCompass.meal.settings",schema:"foodCompass.meal.schemaVersion",session:"foodCompass.meal.sessionExclusions"};
    var mealDefaultFilters = {query:"",categoryIds:MEAL_CATEGORIES.map(function(category){return category.id;}),priceBands:[],flavorTags:[],timeTags:[],fullnessTags:[],sceneTags:[],excludeTags:[],excludeEntryTypes:[],onlyFavorites:false,onlyCustom:false,sort:"source"};
    var mealPersonal = mealLoadPersonal();
    var mealState = {filters:mealCopy(mealDefaultFilters),mode:"wheel",selectedId:null,confirmedId:null,proposedCategoryId:null,lockedCategoryId:null,visible:24,rotation:0,spinning:false,status:"",storageAvailable:true};

    function mealCopy(value){return JSON.parse(JSON.stringify(value));}
    function mealRead(storage,key,fallback){try{var raw=storage.getItem(key);return raw===null?fallback:JSON.parse(raw);}catch(error){mealState&& (mealState.storageAvailable=false);return fallback;}}
    function mealLoadPersonal(){return {customFoods:mealRead(localStorage,MEAL_KEYS.custom,[]),favorites:mealRead(localStorage,MEAL_KEYS.favorites,[]),permanentlyExcluded:mealRead(localStorage,MEAL_KEYS.excluded,[]),history:mealRead(localStorage,MEAL_KEYS.history,[]).slice(0,50),settings:mealRead(localStorage,MEAL_KEYS.settings,{avoidRecent:true}),sessionExclusions:mealRead(sessionStorage,MEAL_KEYS.session,[])}};
    function mealSave(){try{localStorage.setItem(MEAL_KEYS.custom,JSON.stringify(mealPersonal.customFoods));localStorage.setItem(MEAL_KEYS.favorites,JSON.stringify(mealPersonal.favorites));localStorage.setItem(MEAL_KEYS.excluded,JSON.stringify(mealPersonal.permanentlyExcluded));localStorage.setItem(MEAL_KEYS.history,JSON.stringify(mealPersonal.history.slice(0,50)));localStorage.setItem(MEAL_KEYS.settings,JSON.stringify(mealPersonal.settings));localStorage.setItem(MEAL_KEYS.schema,"1");sessionStorage.setItem(MEAL_KEYS.session,JSON.stringify(mealPersonal.sessionExclusions));mealState.storageAvailable=true;}catch(error){mealState.storageAvailable=false;}mealRenderAll();}
    function mealFoods(){return MEAL_FOODS.concat(mealPersonal.customFoods);}
    function mealById(id){return mealFoods().find(function(food){return food.id===id;})||null;}
    function mealCategory(id){return MEAL_CATEGORIES.find(function(category){return category.id===id;});}
    function mealToggle(list,value){return list.includes(value)?list.filter(function(item){return item!==value;}):list.concat(value);}
    function mealIntersects(selected,actual){return !selected.length||selected.some(function(value){return actual.includes(value);});}
    function mealVisibleFoods(){var filters=mealState.filters;var query=filters.query.trim().toLocaleLowerCase("zh-CN");var foods=mealFoods().filter(function(food){if(!food.enabled||mealPersonal.permanentlyExcluded.includes(food.id))return false;if(filters.onlyFavorites&&!mealPersonal.favorites.includes(food.id))return false;if(filters.onlyCustom&&food.source!=="custom")return false;if(filters.excludeEntryTypes.includes(food.entryType))return false;if(filters.categoryIds.length&&!filters.categoryIds.includes(food.categoryId))return false;if(!mealIntersects(filters.priceBands,food.priceBands)||!mealIntersects(filters.flavorTags,food.flavorTags)||!mealIntersects(filters.timeTags,food.timeTags)||!mealIntersects(filters.fullnessTags,food.fullnessTags)||!mealIntersects(filters.sceneTags,food.sceneTags))return false;if(query&&![food.name].concat(food.aliases||[]).some(function(text){return text.toLocaleLowerCase("zh-CN").includes(query);}))return false;for(var index=0;index<filters.excludeTags.length;index+=1){var tag=filters.excludeTags[index];if(tag==="mala"&&food.flavorTags.includes("mala"))return false;if(tag==="vegetarian_friendly"&&!food.dietTags.includes("vegetarian_friendly"))return false;if(tag!=="mala"&&tag!=="vegetarian_friendly"&&food.excludeTags.includes(tag))return false;}return true;});var priceOrder=["under15","15_25","25_40","40_70","70_plus"],timeOrder=["fast","normal","slow"];if(filters.sort==="name")foods.sort(function(a,b){return a.name.localeCompare(b.name,"zh-CN");});if(filters.sort==="price")foods.sort(function(a,b){return Math.min.apply(null,a.priceBands.map(function(tag){return priceOrder.indexOf(tag);}))-Math.min.apply(null,b.priceBands.map(function(tag){return priceOrder.indexOf(tag);}));});if(filters.sort==="time")foods.sort(function(a,b){return Math.min.apply(null,a.timeTags.map(function(tag){return timeOrder.indexOf(tag);}))-Math.min.apply(null,b.timeTags.map(function(tag){return timeOrder.indexOf(tag);}));});if(filters.sort==="recent")foods.sort(function(a,b){return (b.createdAt||"").localeCompare(a.createdAt||"");});return foods;}
    function mealRandomPool(){var base=mealVisibleFoods().filter(function(food){return !mealPersonal.sessionExclusions.includes(food.id);});if(!mealPersonal.settings.avoidRecent)return {foods:base,relaxed:"none"};var recent=mealPersonal.history.slice(0,3).map(function(entry){return entry.foodId;}),avoided=base.filter(function(food){return !recent.includes(food.id);});if(avoided.length)return {foods:avoided,relaxed:"none"};var oldest=recent[recent.length-1],restored=base.filter(function(food){return food.id===oldest||!recent.includes(food.id);});if(restored.length)return {foods:restored,relaxed:"oldest"};return {foods:base,relaxed:"all"};}
    function mealPickBalanced(foods){var categoryIds=MEAL_CATEGORIES.map(function(category){return category.id;}).filter(function(id){return foods.some(function(food){return food.categoryId===id;});});if(!categoryIds.length)return null;var categoryIndex=Math.floor(Math.random()*categoryIds.length),categoryId=categoryIds[categoryIndex],categoryFoods=foods.filter(function(food){return food.categoryId===categoryId;});return {food:categoryFoods[Math.floor(Math.random()*categoryFoods.length)],categoryId:categoryId,categoryIndex:categoryIndex,categoryIds:categoryIds};}
    function mealResetWheelStage(){mealState.proposedCategoryId=null;mealState.lockedCategoryId=null;}
    function mealIsFoodStage(){return mealState.filters.categoryIds.length>0||mealState.lockedCategoryId!==null;}
    function mealFoodStagePool(){var foods=mealRandomPool().foods;return mealState.lockedCategoryId&&!mealState.filters.categoryIds.length?foods.filter(function(food){return food.categoryId===mealState.lockedCategoryId;}):foods;}
    function mealWheelDisplayFoods(foods){var groups=MEAL_CATEGORIES.map(function(category){return foods.filter(function(food){return food.categoryId===category.id;});}).filter(function(group){return group.length;}),visible=[],limit=Math.min(24,foods.length),row=0;while(visible.length<limit){var added=false;groups.forEach(function(group){if(visible.length<limit&&group[row]){visible.push(group[row]);added=true;}});if(!added)break;row+=1;}return visible;}
    function mealWheelColor(categoryIndex){return cssColor(COLORS[categoryIndex%COLORS.length]);}
    function mealFormatPrice(bands){if(!bands.length)return "价格未填写";var order=["under15","15_25","25_40","40_70","70_plus"],selected=order.filter(function(tag){return bands.includes(tag);});if(selected.length===1)return MEAL_PRICE[selected[0]];var low={under15:0,"15_25":15,"25_40":25,"40_70":40,"70_plus":70},high={under15:15,"15_25":25,"25_40":40,"40_70":70,"70_plus":null},first=selected[0],last=selected[selected.length-1];return high[last]===null?"约 "+low[first]+" 元以上":"约 "+low[first]+"～"+high[last]+" 元";}
    function mealPills(target,values,selected,labels,attribute){byId(target).innerHTML=values.map(function(value){return '<button class="pill'+(selected.includes(value)?' active':'')+'" data-'+attribute+'="'+escapeHtml(value)+'" type="button">'+escapeHtml(labels[value]||value)+'</button>';}).join("");}
    function mealRenderFilters(){var allCategories=mealState.filters.categoryIds.length===MEAL_CATEGORIES.length;byId("mealSelectAllCategories").textContent=allCategories?"取消全选":"一键全选";byId("mealSelectAllCategories").classList.toggle("active",allCategories);mealPills("mealCategoryPills",MEAL_CATEGORIES.map(function(item){return item.id;}),mealState.filters.categoryIds,Object.fromEntries(MEAL_CATEGORIES.map(function(item){return [item.id,item.name];})),"meal-category");mealPills("mealPricePills",Object.keys(MEAL_PRICE),mealState.filters.priceBands,MEAL_PRICE,"meal-price");mealPills("mealFlavorPills",Object.keys(MEAL_FLAVOR),mealState.filters.flavorTags,MEAL_FLAVOR,"meal-flavor");mealPills("mealTimePills",Object.keys(MEAL_TIME),mealState.filters.timeTags,MEAL_TIME,"meal-time");mealPills("mealFullnessPills",Object.keys(MEAL_FULLNESS),mealState.filters.fullnessTags,MEAL_FULLNESS,"meal-fullness");mealPills("mealScenePills",Object.keys(MEAL_SCENE),mealState.filters.sceneTags,MEAL_SCENE,"meal-scene");mealPills("mealExcludePills",Object.keys(MEAL_EXCLUDE),mealState.filters.excludeTags,MEAL_EXCLUDE,"meal-exclude");byId("mealSearchInput").value=mealState.filters.query;byId("mealOnlyFavorites").checked=mealState.filters.onlyFavorites;byId("mealOnlyCustom").checked=mealState.filters.onlyCustom;byId("mealAvoidRecent").checked=mealPersonal.settings.avoidRecent;byId("mealRestoreSession").style.display=mealPersonal.sessionExclusions.length?"block":"none";var presets=[{id:"random",label:"随便吃"},{id:"under20",label:"20 元内"},{id:"hurry",label:"赶时间"},{id:"light",label:"清淡一点"},{id:"spicy",label:"想吃辣的"},{id:"treat",label:"吃顿好的"},{id:"solo",label:"一个人"},{id:"group",label:"多人聚餐"}];byId("mealPresetPills").innerHTML=presets.map(function(item){return '<button class="pill'+(mealPresetActive(item.id)?' active':'')+'" data-meal-preset="'+item.id+'" type="button">'+item.label+'</button>';}).join("");}
    function mealPreset(id){var filters=mealCopy(mealDefaultFilters);if(id==="under20")filters.priceBands=["under15","15_25"];if(id==="hurry")filters.timeTags=["fast"];if(id==="light"){filters.flavorTags=["light"];filters.excludeTags=["mala","fried"];}if(id==="spicy")filters.flavorTags=["mala","sour_spicy"];if(id==="treat"){filters.priceBands=["40_70","70_plus"];filters.timeTags=["normal","slow"];}if(id==="solo"){filters.sceneTags=["solo"];filters.excludeEntryTypes=["restaurant"];}if(id==="group")filters.sceneTags=["group","small_group"];return filters;}
    function mealPresetActive(id){var left=mealCopy(mealState.filters),right=mealPreset(id);left.sort="source";return JSON.stringify(left)===JSON.stringify(right);}
    function mealApplyPreset(id){mealState.filters=mealPresetActive(id)?mealCopy(mealDefaultFilters):mealPreset(id);mealState.selectedId=null;mealState.visible=24;mealResetWheelStage();mealRenderAll();}
    function mealRenderCards(){var foods=mealVisibleFoods(),visible=foods.slice(0,mealState.visible);byId("mealProductGrid").innerHTML=visible.length?visible.map(function(food){return '<button class="meal-product-card'+(mealState.selectedId===food.id?' selected':'')+'" data-meal-food="'+escapeHtml(food.id)+'" type="button"><span class="card-brand">'+escapeHtml(mealCategory(food.categoryId).name)+(food.source==="custom"?' · 自定义':'')+'</span><h3>'+escapeHtml(food.name)+'</h3><span class="meal-card-note">'+escapeHtml(mealFormatPrice(food.priceBands))+' · '+escapeHtml(food.timeTags.map(function(tag){return MEAL_TIME[tag];}).join(" / ")||"时间未填写")+'</span></button>';}).join(""):'<div class="empty" style="grid-column:1/-1"><h3>没有符合全部条件的选项</h3><p>建议放宽预算、用餐时间或排除条件。</p></div>';byId("mealLoadMore").style.display=mealState.visible<foods.length?"block":"none";}
    function mealDrawWheel(){var canvas=byId("mealWheelCanvas"),context=canvas.getContext("2d"),size=canvas.width,center=size/2,randomPool=mealRandomPool(),foodStage=mealIsFoodStage(),foods=foodStage?mealFoodStagePool():randomPool.foods,categories=MEAL_CATEGORIES.filter(function(category){return foods.some(function(food){return food.categoryId===category.id;});}),segments=foodStage?mealWheelDisplayFoods(foods):categories,locked=mealState.lockedCategoryId&&mealCategory(mealState.lockedCategoryId);byId("mealWheelStageLabel").textContent=foodStage?"具体食物转盘":"第一步 · 选择大类";byId("mealWheelTitle").textContent=locked&&!mealState.filters.categoryIds.length?"从"+locked.name+"中选一个":foodStage?"从所选分类中直接选一个":"先决定今天吃哪一类";byId("mealBackCategory").style.display=locked&&!mealState.filters.categoryIds.length?"block":"none";byId("mealWheelHint").textContent=foodStage?"盘面展示 "+segments.length+" 个代表选项，最终结果从全部 "+foods.length+" 个候选中产生。":"先抽大类并确认，再进入该分类的具体食物转盘。";byId("mealCategoryDecision").style.display=mealState.proposedCategoryId&&!foodStage?"block":"none";if(mealState.proposedCategoryId)byId("mealProposedCategory").textContent=mealCategory(mealState.proposedCategoryId).name;if(!mealState.spinning)byId("mealSpinButton").textContent=foodStage?"转一道":mealState.proposedCategoryId?"换一类":"转大类";context.clearRect(0,0,size,size);if(!segments.length){context.fillStyle=cssColor("--color-canvas-empty");context.beginPath();context.arc(center,center,center-10,0,Math.PI*2);context.fill();context.fillStyle=cssColor("--color-canvas-muted");context.font="700 24px Microsoft YaHei UI";context.textAlign="center";context.fillText("暂无候选食物",center,center);byId("mealSpinButton").disabled=true;return;}byId("mealSpinButton").disabled=mealState.spinning;var segment=Math.PI*2/segments.length;segments.forEach(function(item,index){var category=foodStage?mealCategory(item.categoryId):item,categoryIndex=MEAL_CATEGORIES.findIndex(function(candidate){return candidate.id===category.id;}),start=-Math.PI/2+index*segment,end=start+segment;context.beginPath();context.moveTo(center,center);context.arc(center,center,center-10,start,end);context.closePath();context.fillStyle=mealWheelColor(categoryIndex,foodStage?index:undefined);context.fill();context.strokeStyle="rgba(255,255,255,.58)";context.lineWidth=2;context.stroke();});context.beginPath();context.arc(center,center,82,0,Math.PI*2);context.fillStyle=cssColor("--color-forest-brand");context.fill();}
    function mealSpin(){var pool=mealRandomPool();if(mealState.spinning||!pool.foods.length)return;if(!mealIsFoodStage()){var categoryIds=MEAL_CATEGORIES.map(function(category){return category.id;}).filter(function(id){return pool.foods.some(function(food){return food.categoryId===id;});}),categoryIndex=Math.floor(Math.random()*categoryIds.length),categoryId=categoryIds[categoryIndex],categorySegment=360/categoryIds.length;mealState.spinning=true;mealState.rotation+=2160+(360-(categoryIndex+.5)*categorySegment);byId("mealWheelCanvas").style.transform="rotate("+mealState.rotation+"deg)";byId("mealSpinButton").disabled=true;byId("mealSpinButton").textContent="转动中";setTimeout(function(){mealState.spinning=false;mealState.proposedCategoryId=categoryId;mealState.selectedId=null;mealRenderAll();},prefersReducedMotion()?80:2400);return;}var foods=mealFoodStagePool();if(foods.length===1){mealSelect(foods[0].id,'只剩“'+foods[0].name+'”，看来今天就是它了。');return;}var picked=mealPickBalanced(foods),visible=mealWheelDisplayFoods(foods),visibleIndex=Math.max(0,visible.findIndex(function(food){return food.id===picked.food.id;})),segment=360/Math.max(1,visible.length);mealState.spinning=true;mealState.rotation+=2160+(360-(visibleIndex+.5)*segment);byId("mealWheelCanvas").style.transform="rotate("+mealState.rotation+"deg)";byId("mealSpinButton").disabled=true;byId("mealSpinButton").textContent="转动中";setTimeout(function(){mealState.spinning=false;mealSelect(picked.food.id,pool.relaxed==="none"?"":"为保留可选项，已放宽最近三次防重复。");},prefersReducedMotion()?80:2400);}
    function mealSelect(id,status){mealState.selectedId=id;mealState.confirmedId=null;mealState.status=status||"";mealRenderAll();}
    function mealRenderResult(){var food=mealById(mealState.selectedId),html="";if(food){var favorite=mealPersonal.favorites.includes(food.id);html='<section class="result"><div class="result-head"><p class="result-brand">今天吃 · '+escapeHtml(mealCategory(food.categoryId).name)+'</p><h2>'+escapeHtml(food.name)+'</h2><div class="result-summary"><span>'+(food.entryType==="restaurant"?'餐厅 / 食堂窗口':'具体食物')+(food.source==="custom"?' · 自定义':'')+'</span><strong>'+escapeHtml(mealFormatPrice(food.priceBands))+'</strong></div></div><div class="result-body"><div class="meal-info-grid">'+mealInfo("口味",food.flavorTags.map(function(tag){return MEAL_FLAVOR[tag];}).join(" · ")||"未填写")+mealInfo("饱腹程度",food.fullnessTags.map(function(tag){return MEAL_FULLNESS[tag];}).join(" / ")||"未填写")+mealInfo("用餐时间",food.timeTags.map(function(tag){return MEAL_TIME[tag];}).join(" / ")||"未填写")+mealInfo("适用场景",food.sceneTags.map(function(tag){return MEAL_SCENE[tag];}).join(" · ")||"未填写")+(food.note?mealInfo("位置或备注",food.note):"")+'</div><p class="disclaimer">标签均为一般化参考，实际情况请以门店为准。</p>'+(mealState.status?'<p class="meal-status">'+escapeHtml(mealState.status)+'</p>':'')+'<div class="meal-result-actions"><button class="meal-confirm" data-meal-action="confirm" type="button"'+(mealState.confirmedId===food.id?' disabled':'')+'>'+(mealState.confirmedId===food.id?'已记入最近吃过':'就吃这个')+'</button><button class="meal-again" data-meal-action="again" type="button">再转一次</button><button data-meal-action="session" type="button">本轮排除</button></div><div class="meal-secondary-actions"><button data-meal-action="same" type="button">换个同类</button><button data-meal-action="different" type="button">完全换口味</button><button data-meal-action="favorite" type="button">'+(favorite?'取消收藏':'收藏')+'</button><button data-meal-action="permanent" type="button">永久排除</button>'+(food.source==="custom"?'<button data-meal-action="edit" type="button">编辑</button>':'')+'</div></div></section>';}
      byId("mealBrowseResultSlot").innerHTML=mealState.mode==="browse"?html:"";byId("mealWheelResultSlot").innerHTML=mealState.mode==="wheel"?html:"";
    }
    function mealInfo(label,value){return '<div class="meal-info"><span>'+escapeHtml(label)+'</span><strong>'+escapeHtml(value)+'</strong></div>';}
    function mealResultAction(action){var food=mealById(mealState.selectedId);if(!food)return;if(action==="confirm"&&mealState.confirmedId!==food.id){mealPersonal.history.unshift({foodId:food.id,foodName:food.name,categoryId:food.categoryId,selectedAt:new Date().toISOString(),source:food.source});mealPersonal.history=mealPersonal.history.slice(0,50);mealState.confirmedId=food.id;mealState.status="已记入最近吃过。";mealSave();}if(action==="again")mealSpin();if(action==="session"){mealPersonal.sessionExclusions=Array.from(new Set(mealPersonal.sessionExclusions.concat(food.id)));mealState.selectedId=null;mealState.status='本轮已排除“'+food.name+'”。';mealSave();}if(action==="favorite"){mealPersonal.favorites=mealToggle(mealPersonal.favorites,food.id);mealSave();}if(action==="permanent"){mealPersonal.permanentlyExcluded=Array.from(new Set(mealPersonal.permanentlyExcluded.concat(food.id)));mealState.selectedId=null;mealState.status="已永久排除。";mealSave();}if(action==="same"){var same=mealRandomPool().foods.filter(function(item){return item.categoryId===food.categoryId&&item.id!==food.id;}),next=same.length?same[Math.floor(Math.random()*same.length)]:mealRandomPool().foods.find(function(item){return item.categoryId===food.categoryId;});if(next)mealSelect(next.id);}if(action==="different"){var different=mealRandomPool().foods.filter(function(item){return item.categoryId!==food.categoryId;}),picked=mealPickBalanced(different.length?different:mealRandomPool().foods);mealResetWheelStage();if(picked)mealSelect(picked.food.id);}if(action==="edit"){mealOpenManager("custom");mealEditCustom(food.id);}}
    function mealRenderMode(){document.querySelectorAll("[data-meal-mode]").forEach(function(button){button.classList.toggle("active",button.dataset.mealMode===mealState.mode);});byId("mealBrowseMode").classList.toggle("hidden",mealState.mode!=="browse");byId("mealWheelMode").classList.toggle("hidden",mealState.mode!=="wheel");byId("mealSortWrap").style.display=mealState.mode==="browse"?"block":"none";setTimeout(mealDrawWheel,0);}
    function mealRenderAll(){mealRenderFilters();var active=mealState.mode==="wheel"?mealRandomPool().foods:mealVisibleFoods(),categoryCount=MEAL_CATEGORIES.filter(function(category){return active.some(function(food){return food.categoryId===category.id;});}).length;byId("mealCandidateCount").textContent=active.length;byId("mealCategoryCount").textContent=categoryCount;byId("offlineCustomCount").textContent=mealPersonal.customFoods.length;byId("offlineMealCategoryGrid").innerHTML=MEAL_CATEGORIES.map(function(category){return '<article class="brand-data-card"><h2>'+escapeHtml(category.name)+'</h2><dl><div><dt>内置选项</dt><dd>'+MEAL_FOODS.filter(function(food){return food.categoryId===category.id;}).length+'</dd></div></dl></article>';}).join("");mealRenderCards();mealRenderResult();mealRenderMode();mealRenderManager();}
    function mealOpenManager(tab){byId("mealManager").classList.add("open");mealSetManagerTab(tab||"custom");}
    function mealCloseManager(){byId("mealManager").classList.remove("open");}
    function mealSetManagerTab(tab){document.querySelectorAll("[data-meal-tab]").forEach(function(button){button.classList.toggle("active",button.dataset.mealTab===tab);});document.querySelectorAll("[data-meal-panel]").forEach(function(panel){panel.classList.toggle("active",panel.dataset.mealPanel===tab);});}
    function mealListHtml(ids,action,label){var foods=ids.map(mealById).filter(Boolean);return foods.length?foods.map(function(food){return '<div class="meal-list-item"><div><strong>'+escapeHtml(food.name)+'</strong><small>'+escapeHtml(mealCategory(food.categoryId).name)+'</small></div><button data-meal-list-action="'+action+'" data-meal-id="'+escapeHtml(food.id)+'" type="button">'+label+'</button></div>';}).join(""):'<p class="count">暂无记录。</p>';}
    function mealRenderManager(){if(!byId("mealManager"))return;byId("mealCustomList").innerHTML=mealPersonal.customFoods.length?mealPersonal.customFoods.map(function(food){return '<div class="meal-list-item"><div><strong>'+escapeHtml(food.name)+'</strong><small>'+escapeHtml(mealCategory(food.categoryId).name)+(food.note?' · '+escapeHtml(food.note):'')+'</small></div><span><button data-meal-list-action="edit" data-meal-id="'+food.id+'" type="button">编辑</button> <button data-meal-list-action="delete" data-meal-id="'+food.id+'" type="button">删除</button></span></div>';}).join(""):'<p class="count">还没有自定义食物。</p>';byId("mealFavoriteList").innerHTML=mealListHtml(mealPersonal.favorites,"unfavorite","取消收藏");byId("mealExcludedList").innerHTML=mealListHtml(mealPersonal.permanentlyExcluded,"restore","恢复");byId("mealHistoryList").innerHTML=mealPersonal.history.length?mealPersonal.history.map(function(entry,index){return '<div class="meal-list-item"><button data-meal-list-action="history-open" data-meal-id="'+escapeHtml(entry.foodId)+'" type="button"><strong>'+escapeHtml(entry.foodName)+'</strong><small>'+escapeHtml(new Date(entry.selectedAt).toLocaleString("zh-CN"))+'</small></button><button data-meal-list-action="history-delete" data-meal-index="'+index+'" type="button">删除</button></div>';}).join(""):'<p class="count">点击“就吃这个”后会留下记录。</p>';}
    function mealCreateFormGroups(){var groups=[{name:"price",title:"价格",values:Object.keys(MEAL_PRICE),labels:MEAL_PRICE},{name:"flavor",title:"口味",values:Object.keys(MEAL_FLAVOR),labels:MEAL_FLAVOR},{name:"time",title:"用餐时间",values:Object.keys(MEAL_TIME),labels:MEAL_TIME},{name:"fullness",title:"饱腹程度",values:Object.keys(MEAL_FULLNESS),labels:MEAL_FULLNESS},{name:"scene",title:"适用场景",values:Object.keys(MEAL_SCENE),labels:MEAL_SCENE},{name:"exclude",title:"常见食材 / 形态标签",values:Object.keys(MEAL_EXCLUDE).filter(function(tag){return tag!=="mala"&&tag!=="vegetarian_friendly";}),labels:MEAL_EXCLUDE}];byId("mealCustomGroups").innerHTML=groups.map(function(group){return '<div class="field"><span class="field-title">'+group.title+'</span><div class="choice-pills">'+group.values.map(function(value){return '<label class="pill"><input name="meal-custom-'+group.name+'" type="checkbox" value="'+value+'"> '+group.labels[value]+'</label>';}).join("")+'</div></div>';}).join("")+'<label class="meal-check"><input name="meal-custom-vegetarian" type="checkbox">素食友好（仅作一般参考）</label>';}
    function mealEditCustom(id){var food=mealById(id);if(!food||food.source!=="custom")return;byId("mealEditId").value=food.id;byId("mealCustomName").value=food.name;byId("mealCustomCategory").value=food.categoryId;byId("mealCustomType").value=food.entryType;byId("mealCustomNote").value=food.note||"";[["price",food.priceBands],["flavor",food.flavorTags],["time",food.timeTags],["fullness",food.fullnessTags],["scene",food.sceneTags],["exclude",food.excludeTags]].forEach(function(pair){document.querySelectorAll('[name="meal-custom-'+pair[0]+'"]').forEach(function(input){input.checked=pair[1].includes(input.value);});});document.querySelector('[name="meal-custom-vegetarian"]').checked=food.dietTags.includes("vegetarian_friendly");}
    function mealResetCustomForm(){byId("mealCustomForm").reset();byId("mealEditId").value="";}
    function mealFormValues(name){return Array.from(document.querySelectorAll('[name="meal-custom-'+name+'"]:checked')).map(function(input){return input.value;});}
    function mealShowManagerMessage(message){var element=byId("mealManagerMessage");element.textContent=message;element.style.display="block";}
    function mealValidateImport(value){if(!value||typeof value!=="object"||value.schemaVersion!==1)throw new Error("仅支持 schemaVersion 为 1 的备份文件。");if(!Array.isArray(value.customFoods)||!Array.isArray(value.favorites)||!Array.isArray(value.permanentlyExcluded)||!Array.isArray(value.history)||!value.settings||typeof value.settings.avoidRecent!=="boolean")throw new Error("个人数据字段不完整。");if(!value.customFoods.every(function(food){return food&&food.source==="custom"&&typeof food.id==="string"&&typeof food.name==="string"&&MEAL_CATEGORIES.some(function(category){return category.id===food.categoryId;});}))throw new Error("自定义食物格式不正确。");return value;}
    function mealImportData(incoming,mode){var base=mode==="merge"?mealPersonal:{customFoods:[],favorites:[],permanentlyExcluded:[],history:[],settings:{avoidRecent:true},sessionExclusions:[]},used=new Set(MEAL_FOODS.map(function(food){return food.id;}).concat(base.customFoods.map(function(food){return food.id;}))),remap={},customFoods=base.customFoods.slice();incoming.customFoods.forEach(function(food){var existing=customFoods.find(function(item){return item.id===food.id;});if(existing&&JSON.stringify(existing)===JSON.stringify(food)){remap[food.id]=food.id;return;}var id=food.id;while(used.has(id))id="custom-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);used.add(id);remap[food.id]=id;customFoods.push(Object.assign({},food,{id:id,source:"custom"}));});var mapId=function(id){return remap[id]||id;},known=new Set(MEAL_FOODS.map(function(food){return food.id;}).concat(customFoods.map(function(food){return food.id;}))),uniqueKnown=function(values){return Array.from(new Set(values.map(mapId))).filter(function(id){return known.has(id);});},history=base.history.concat(incoming.history.map(function(entry){return Object.assign({},entry,{foodId:mapId(entry.foodId)});})).sort(function(a,b){return b.selectedAt.localeCompare(a.selectedAt);}),seen=new Set();history=history.filter(function(entry){var key=entry.foodId+"|"+entry.selectedAt;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,50);mealPersonal={customFoods:customFoods,favorites:uniqueKnown(base.favorites.concat(incoming.favorites)),permanentlyExcluded:uniqueKnown(base.permanentlyExcluded.concat(incoming.permanentlyExcluded)),history:history,settings:incoming.settings,sessionExclusions:mode==="merge"?base.sessionExclusions:[]};mealSave();}

    document.querySelectorAll("[data-meal-mode]").forEach(function(button){button.addEventListener("click",function(){mealState.mode=button.dataset.mealMode;mealRenderAll();});});
    byId("mealSelectAllCategories").addEventListener("click",function(){mealState.filters.categoryIds=mealState.filters.categoryIds.length===MEAL_CATEGORIES.length?[]:MEAL_CATEGORIES.map(function(category){return category.id;});mealState.selectedId=null;mealResetWheelStage();mealRenderAll();});
    [["mealCategoryPills","mealCategory","categoryIds"],["mealPricePills","mealPrice","priceBands"],["mealFlavorPills","mealFlavor","flavorTags"],["mealTimePills","mealTime","timeTags"],["mealFullnessPills","mealFullness","fullnessTags"],["mealScenePills","mealScene","sceneTags"],["mealExcludePills","mealExclude","excludeTags"]].forEach(function(config){byId(config[0]).addEventListener("click",function(event){var button=event.target.closest("[data-"+config[1].replace(/[A-Z]/g,function(letter){return "-"+letter.toLowerCase();})+"]");if(!button)return;mealState.filters[config[2]]=mealToggle(mealState.filters[config[2]],button.dataset[config[1]]);mealState.selectedId=null;mealState.visible=24;mealResetWheelStage();mealRenderAll();});});
    byId("mealPresetPills").addEventListener("click",function(event){var button=event.target.closest("[data-meal-preset]");if(button)mealApplyPreset(button.dataset.mealPreset);});
    byId("mealSearchInput").addEventListener("input",function(event){mealState.filters.query=event.target.value;mealState.visible=24;mealState.selectedId=null;mealResetWheelStage();mealRenderAll();});
    byId("mealOnlyFavorites").addEventListener("change",function(event){mealState.filters.onlyFavorites=event.target.checked;mealResetWheelStage();mealRenderAll();});byId("mealOnlyCustom").addEventListener("change",function(event){mealState.filters.onlyCustom=event.target.checked;mealResetWheelStage();mealRenderAll();});byId("mealAvoidRecent").addEventListener("change",function(event){mealPersonal.settings.avoidRecent=event.target.checked;mealResetWheelStage();mealSave();});
    byId("mealSortSelect").addEventListener("change",function(event){mealState.filters.sort=event.target.value;mealRenderAll();});byId("mealResetFilters").addEventListener("click",function(){mealState.filters=mealCopy(mealDefaultFilters);mealState.selectedId=null;mealResetWheelStage();mealRenderAll();});byId("mealRestoreSession").addEventListener("click",function(){mealPersonal.sessionExclusions=[];mealSave();});byId("mealLoadMore").addEventListener("click",function(){mealState.visible+=24;mealRenderAll();});byId("mealSpinButton").addEventListener("click",mealSpin);
    byId("mealConfirmCategory").addEventListener("click",function(){if(!mealState.proposedCategoryId)return;mealState.lockedCategoryId=mealState.proposedCategoryId;mealState.proposedCategoryId=null;mealState.selectedId=null;mealRenderAll();});byId("mealRetryCategory").addEventListener("click",mealSpin);byId("mealBackCategory").addEventListener("click",function(){mealResetWheelStage();mealState.selectedId=null;mealRenderAll();});
    byId("mealProductGrid").addEventListener("click",function(event){var button=event.target.closest("[data-meal-food]");if(button)mealSelect(button.dataset.mealFood);});document.querySelectorAll("#mealBrowseResultSlot,#mealWheelResultSlot").forEach(function(slot){slot.addEventListener("click",function(event){var button=event.target.closest("[data-meal-action]");if(button)mealResultAction(button.dataset.mealAction);});});
    byId("mealOpenManager").addEventListener("click",function(){mealOpenManager();});byId("mealCloseManager").addEventListener("click",mealCloseManager);byId("mealManager").addEventListener("mousedown",function(event){if(event.target===event.currentTarget)mealCloseManager();});window.addEventListener("keydown",function(event){if(event.key==="Escape")mealCloseManager();});byId("mealManagerTabs").addEventListener("click",function(event){var button=event.target.closest("[data-meal-tab]");if(button)mealSetManagerTab(button.dataset.mealTab);});
    byId("mealCustomForm").addEventListener("submit",function(event){event.preventDefault();var id=byId("mealEditId").value,name=byId("mealCustomName").value.trim();if(!name)return;var existing=id?mealById(id):null,food={id:id||"custom-"+Date.now()+"-"+Math.random().toString(36).slice(2,8),name:name,aliases:existing&&existing.aliases||[],categoryId:byId("mealCustomCategory").value,entryType:byId("mealCustomType").value,priceBands:mealFormValues("price"),flavorTags:mealFormValues("flavor"),timeTags:mealFormValues("time"),fullnessTags:mealFormValues("fullness"),sceneTags:mealFormValues("scene"),excludeTags:mealFormValues("exclude"),dietTags:document.querySelector('[name="meal-custom-vegetarian"]').checked?["vegetarian_friendly"]:[],source:"custom",enabled:true,note:byId("mealCustomNote").value.trim(),createdAt:existing&&existing.createdAt||new Date().toISOString()};mealPersonal.customFoods=id?mealPersonal.customFoods.map(function(item){return item.id===id?food:item;}):[food].concat(mealPersonal.customFoods);mealResetCustomForm();mealShowManagerMessage(id?"自定义食物已更新。":"自定义食物已添加。");mealSave();});byId("mealCancelEdit").addEventListener("click",mealResetCustomForm);
    byId("mealManager").addEventListener("click",function(event){var button=event.target.closest("[data-meal-list-action]");if(!button)return;var action=button.dataset.mealListAction,id=button.dataset.mealId;if(action==="edit")mealEditCustom(id);if(action==="delete"){mealPersonal.customFoods=mealPersonal.customFoods.filter(function(food){return food.id!==id;});mealPersonal.favorites=mealPersonal.favorites.filter(function(item){return item!==id;});mealPersonal.permanentlyExcluded=mealPersonal.permanentlyExcluded.filter(function(item){return item!==id;});mealSave();}if(action==="unfavorite"){mealPersonal.favorites=mealPersonal.favorites.filter(function(item){return item!==id;});mealSave();}if(action==="restore"){mealPersonal.permanentlyExcluded=mealPersonal.permanentlyExcluded.filter(function(item){return item!==id;});mealSave();}if(action==="history-open"){mealCloseManager();mealState.mode="browse";mealSelect(id);}if(action==="history-delete"){mealPersonal.history.splice(Number(button.dataset.mealIndex),1);mealSave();}});
    byId("mealClearHistory").addEventListener("click",function(){mealPersonal.history=[];mealSave();});byId("mealExport").addEventListener("click",function(){var payload={schemaVersion:1,exportedAt:new Date().toISOString(),customFoods:mealPersonal.customFoods,favorites:mealPersonal.favorites,permanentlyExcluded:mealPersonal.permanentlyExcluded,history:mealPersonal.history,settings:mealPersonal.settings},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json;charset=utf-8"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="食物罗盘-我的食物库-"+new Date().toISOString().slice(0,10)+".json";anchor.click();URL.revokeObjectURL(url);});byId("mealImport").addEventListener("change",function(event){var file=event.target.files&&event.target.files[0];if(!file)return;file.text().then(function(text){var incoming=mealValidateImport(JSON.parse(text)),mode=document.querySelector('[name="mealImportMode"]:checked').value;mealImportData(incoming,mode);mealShowManagerMessage(mode==="merge"?"导入完成，个人数据已合并。":"导入完成，个人数据已覆盖。");}).catch(function(error){mealShowManagerMessage("导入失败："+(error.message||"文件格式不正确"));});});
    document.querySelectorAll("[data-offline-data]").forEach(function(button){button.addEventListener("click",function(){document.querySelectorAll("[data-offline-data]").forEach(function(item){item.classList.toggle("active",item===button);});byId("offlineMealData").classList.toggle("hidden",button.dataset.offlineData!=="meals");byId("offlineCanteenData").classList.toggle("hidden",button.dataset.offlineData!=="canteens");byId("offlineTakeoutData").classList.toggle("hidden",button.dataset.offlineData!=="takeout");byId("offlineMilkData").classList.toggle("hidden",button.dataset.offlineData!=="milk");});});
    byId("mealCustomCategory").innerHTML=MEAL_CATEGORIES.map(function(category){return '<option value="'+category.id+'">'+category.name+'</option>';}).join("");mealCreateFormGroups();window.addEventListener("hashchange",function(){if(location.hash==="#food")setTimeout(mealDrawWheel,0);});mealRenderAll();
