    var TAKEOUT_MODULE_DATA = __TAKEOUT_DATA__;
    var takeoutRefs=TAKEOUT_MODULE_DATA.referenceData;
    var takeoutKeys={customMerchants:"foodCompass.takeout.customMerchants",favorites:"foodCompass.takeout.favorites",permanentExclusions:"foodCompass.takeout.permanentExclusions",history:"foodCompass.takeout.history",settings:"foodCompass.takeout.settings",schemaVersion:"foodCompass.takeout.schemaVersion",sessionExclusions:"foodCompass.takeout.sessionExclusions"};
    var takeoutPresets=[{id:"random",label:"随便点",filters:{}},{id:"nearby",label:"离南门近",filters:{distanceBandIds:["near_gate","km_1_2"]}},{id:"proper",label:"正经吃饭",filters:{categoryIds:["local_cuisine","international","fast_main","hotpot","bbq_grill"]}},{id:"quick",label:"简单快捷",filters:{categoryIds:["fast_main","snacks_late_night","convenience"],distanceBandIds:["near_gate","km_1_2","km_2_3"]}},{id:"late",label:"夜宵",filters:{categoryIds:["bbq_grill","snacks_late_night","convenience"]}},{id:"drink",label:"喝点东西",filters:{categoryIds:["drinks","dessert_bakery"]}},{id:"group",label:"多人聚餐",filters:{categoryIds:["hotpot","bbq_grill","local_cuisine","international"]}}];
    var takeoutDefaultFilters={query:"",categoryIds:[],distanceBandIds:[],areaIds:[],evidenceLevels:["A","B"],onlyFavorites:false,excludeEstimatedDistance:false,sort:"source"};
    var takeoutPersonal={customMerchants:[],favorites:[],permanentExclusions:[],history:[],settings:{avoidRecent:true},sessionExclusions:[]};
    var takeoutState={filters:Object.assign({},takeoutDefaultFilters),mode:"wheel",selectedId:null,confirmedId:null,visible:24,rotation:0,spinning:false};
    var takeoutCategoryById=Object.fromEntries(takeoutRefs.categories.map(function(item){return [item.id,item];}));
    var takeoutAreaById=Object.fromEntries(takeoutRefs.areas.map(function(item){return [item.id,item];}));

    function takeoutRead(storage,key,fallback){try{var raw=storage.getItem(key);return raw===null?fallback:JSON.parse(raw);}catch{byId("takeoutStorageWarning").classList.remove("hidden");return fallback;}}
    function takeoutLoad(){takeoutPersonal.customMerchants=takeoutRead(localStorage,takeoutKeys.customMerchants,[]);takeoutPersonal.favorites=takeoutRead(localStorage,takeoutKeys.favorites,[]);takeoutPersonal.permanentExclusions=takeoutRead(localStorage,takeoutKeys.permanentExclusions,[]);takeoutPersonal.history=takeoutRead(localStorage,takeoutKeys.history,[]).slice(0,50);takeoutPersonal.settings=takeoutRead(localStorage,takeoutKeys.settings,{avoidRecent:true});takeoutPersonal.sessionExclusions=takeoutRead(sessionStorage,takeoutKeys.sessionExclusions,[]);byId("takeoutAvoidRecent").checked=takeoutPersonal.settings.avoidRecent!==false;}
    function takeoutSave(){try{localStorage.setItem(takeoutKeys.customMerchants,JSON.stringify(takeoutPersonal.customMerchants));localStorage.setItem(takeoutKeys.favorites,JSON.stringify(takeoutPersonal.favorites));localStorage.setItem(takeoutKeys.permanentExclusions,JSON.stringify(takeoutPersonal.permanentExclusions));localStorage.setItem(takeoutKeys.history,JSON.stringify(takeoutPersonal.history.slice(0,50)));localStorage.setItem(takeoutKeys.settings,JSON.stringify(takeoutPersonal.settings));localStorage.setItem(takeoutKeys.schemaVersion,"1");sessionStorage.setItem(takeoutKeys.sessionExclusions,JSON.stringify(takeoutPersonal.sessionExclusions));}catch{byId("takeoutStorageWarning").classList.remove("hidden");}}
    function takeoutAll(){return TAKEOUT_MODULE_DATA.merchants.concat(takeoutPersonal.customMerchants);}
    function takeoutToggle(values,value){return values.includes(value)?values.filter(function(item){return item!==value;}):values.concat(value);}
    function takeoutFilter(){var f=takeoutState.filters;var query=f.query.trim().toLocaleLowerCase("zh-CN");var favorites=new Set(takeoutPersonal.favorites);var excluded=new Set(takeoutPersonal.permanentExclusions);var list=takeoutAll().filter(function(item){return item.enabled&&!excluded.has(item.id);}).filter(function(item){return !query||(item.searchText||item.name).toLocaleLowerCase("zh-CN").includes(query);}).filter(function(item){return !f.categoryIds.length||f.categoryIds.includes(item.categoryId);}).filter(function(item){return !f.distanceBandIds.length||f.distanceBandIds.includes(item.location.distanceBandId);}).filter(function(item){return !f.areaIds.length||f.areaIds.includes(item.areaId);}).filter(function(item){return f.evidenceLevels.includes(item.evidence.level);}).filter(function(item){return !f.onlyFavorites||favorites.has(item.id);}).filter(function(item){return !f.excludeEstimatedDistance||!item.location.isEstimated;});return list.sort(function(a,b){if(f.sort==="distance")return (a.location.distanceFromPkuSouthGateKm==null?999:a.location.distanceFromPkuSouthGateKm)-(b.location.distanceFromPkuSouthGateKm==null?999:b.location.distanceFromPkuSouthGateKm);if(f.sort==="name")return a.name.localeCompare(b.name,"zh-CN");if(f.sort==="category")return a.categoryId.localeCompare(b.categoryId)||a.name.localeCompare(b.name,"zh-CN");return a.id.localeCompare(b.id,undefined,{numeric:true});});}
    function takeoutWheelPool(){var session=new Set(takeoutPersonal.sessionExclusions);var pool=takeoutFilter().filter(function(item){return item.wheelEligible&&!session.has(item.id);});if(!takeoutPersonal.settings.avoidRecent)return pool;var recent=takeoutPersonal.history.slice(0,3).map(function(item){return item.merchantId;});for(var count=recent.length;count>=0;count-=1){var excluded=new Set(recent.slice(0,count));var result=pool.filter(function(item){return !excluded.has(item.id);});if(result.length)return result;}return pool;}
    function takeoutBalancedPick(pool){var categoryIds=Array.from(new Set(pool.map(function(item){return item.categoryId;})));if(!categoryIds.length)return null;var categoryId=categoryIds[Math.floor(Math.random()*categoryIds.length)];var categoryPool=pool.filter(function(item){return item.categoryId===categoryId;});return categoryPool[Math.floor(Math.random()*categoryPool.length)];}
    function takeoutSelected(){return takeoutAll().find(function(item){return item.id===takeoutState.selectedId;})||null;}
    function takeoutPills(container,items,selected,dataName){container.innerHTML=items.map(function(item){return '<button class="pill '+(selected.includes(item.id)?'active':'')+'" data-'+dataName+'="'+escapeHtml(item.id)+'" type="button">'+escapeHtml(item.shortLabel||item.name)+'</button>';}).join("");}
    function takeoutPresetActive(preset){var keys=Object.keys(preset.filters);if(!keys.length)return !takeoutState.filters.categoryIds.length&&!takeoutState.filters.distanceBandIds.length&&!takeoutState.filters.areaIds.length;return keys.every(function(key){return JSON.stringify(takeoutState.filters[key])===JSON.stringify(preset.filters[key]);});}
    function takeoutRenderFilters(){byId("takeoutPresets").innerHTML=takeoutPresets.map(function(item){return '<button class="pill '+(takeoutPresetActive(item)?'active':'')+'" data-takeout-preset="'+item.id+'" type="button">'+item.label+'</button>';}).join("");takeoutPills(byId("takeoutCategories"),takeoutRefs.categories,takeoutState.filters.categoryIds,"takeout-category");takeoutPills(byId("takeoutDistances"),takeoutRefs.distanceBands,takeoutState.filters.distanceBandIds,"takeout-distance");takeoutPills(byId("takeoutAreas"),takeoutRefs.areas,takeoutState.filters.areaIds,"takeout-area");takeoutPills(byId("takeoutEvidence"),takeoutRefs.evidenceLevels,takeoutState.filters.evidenceLevels,"takeout-evidence");byId("takeoutOnlyFavorites").checked=takeoutState.filters.onlyFavorites;byId("takeoutExcludeEstimated").checked=takeoutState.filters.excludeEstimatedDistance;byId("takeoutRestoreSession").style.display=takeoutPersonal.sessionExclusions.length?"block":"none";byId("takeoutRestoreSession").textContent="恢复本轮排除（"+takeoutPersonal.sessionExclusions.length+"）";}
    function takeoutCard(item){var category=takeoutCategoryById[item.categoryId]||{};var area=takeoutAreaById[item.areaId]||{};return '<button class="product-card" data-takeout-merchant="'+escapeHtml(item.id)+'" type="button"><div class="card-top"><span class="card-brand">'+escapeHtml(category.name||"自定义商户")+(item.source==="custom"?" · 自定义":"")+'</span><span class="takeout-card-distance">'+escapeHtml(item.location.distanceDisplay)+'</span></div><h3>'+escapeHtml(item.name)+'</h3><p class="takeout-card-meta">'+escapeHtml(item.detailCategory)+' · '+escapeHtml(area.shortLabel||area.name||"")+'<br>配送待平台确认</p></button>';}
    function takeoutRenderBrowse(){var list=takeoutFilter();byId("takeoutGrid").innerHTML=list.slice(0,takeoutState.visible).map(takeoutCard).join("")||'<div class="empty"><h3>没有符合条件的商户</h3><p>可以放宽类型、商圈或距离条件后再试。</p></div>';byId("takeoutLoadMore").style.display=takeoutState.visible<list.length?"block":"none";byId("takeoutLoadMore").textContent="加载更多（还剩 "+Math.max(0,list.length-takeoutState.visible)+" 家）";}
    function takeoutWheelDisplay(pool){if(pool.length<=24)return pool;var groups={};pool.forEach(function(item){(groups[item.categoryId]||(groups[item.categoryId]=[])).push(item);});var result=[];while(result.length<24&&Object.values(groups).some(function(items){return items.length;})){Object.values(groups).forEach(function(items){if(items.length&&result.length<24)result.push(items.shift());});}return result;}
    function takeoutDrawWheel(){var canvas=byId("takeoutWheelCanvas");if(!canvas)return;var context=canvas.getContext("2d");var center=canvas.width/2;var items=takeoutWheelDisplay(takeoutWheelPool());context.clearRect(0,0,canvas.width,canvas.height);if(!items.length){context.beginPath();context.arc(center,center,center-8,0,Math.PI*2);context.fillStyle=cssColor("--color-canvas-empty");context.fill();context.fillStyle=cssColor("--color-canvas-muted");context.font="700 22px Microsoft YaHei UI";context.textAlign="center";context.fillText("暂无候选商户",center,center);byId("takeoutSpin").disabled=true;return;}var step=Math.PI*2/items.length;items.forEach(function(item,index){context.beginPath();context.moveTo(center,center);context.arc(center,center,center-8,-Math.PI/2+index*step,-Math.PI/2+(index+1)*step);context.closePath();var categoryIndex=takeoutRefs.categories.findIndex(function(category){return category.id===item.categoryId;});context.fillStyle=cssColor(COLORS[(categoryIndex+index)%COLORS.length]);context.fill();context.strokeStyle="rgba(255,255,255,.58)";context.stroke();});context.beginPath();context.arc(center,center,78,0,Math.PI*2);context.fillStyle=cssColor("--color-forest-brand");context.fill();byId("takeoutSpin").disabled=takeoutState.spinning;}
    function takeoutSpin(){var pool=takeoutWheelPool();if(takeoutState.spinning||!pool.length)return;var picked=takeoutBalancedPick(pool);takeoutState.spinning=true;takeoutState.rotation+=2160+Math.floor(Math.random()*360);byId("takeoutWheelCanvas").style.transform="rotate("+takeoutState.rotation+"deg)";byId("takeoutSpin").disabled=true;byId("takeoutSpin").textContent="转动中";setTimeout(function(){takeoutState.spinning=false;takeoutState.selectedId=picked.id;takeoutState.confirmedId=null;byId("takeoutSpin").textContent="换一家";takeoutDrawWheel();takeoutRenderResult();},prefersReducedMotion()?80:2400);}
    function takeoutDetails(item){var area=takeoutAreaById[item.areaId]||{};var fields=[["细分类",item.detailCategory],["商圈",area.name],["商场 / 街区",item.place],["地址",item.address],["距离精度",item.location.isEstimated?"商圈/楼宇中心估算":item.location.precisionLabel],["证据等级",item.evidence.level+"级 · "+(item.evidence.level==="A"?"近期/官方确认":"公开地图候选")],["公开参考人均",item.publicReference.averageSpendCny==null?null:item.publicReference.averageSpendCny+" 元"],["营业时间线索",item.publicReference.openingHoursText]];return fields.filter(function(field){return field[1];}).map(function(field){return '<div><dt>'+escapeHtml(field[0])+'</dt><dd>'+escapeHtml(field[1])+'</dd></div>';}).join("");}
    function takeoutRenderResult(){var item=takeoutSelected();var html="";if(item){var category=takeoutCategoryById[item.categoryId]||{};html='<article class="result"><div class="result-head"><p class="result-brand">'+escapeHtml(category.name||"自定义商户")+'</p><h2>'+escapeHtml(item.name)+'</h2><div class="result-summary"><span>距北京大学南门参考距离</span><strong>'+escapeHtml(item.location.distanceDisplay)+'</strong></div></div><div class="result-body"><dl class="takeout-result-grid">'+takeoutDetails(item)+'</dl><p class="takeout-warning">当前未验证美团或饿了么配送，请复制店名后在外卖平台确认。</p><div class="takeout-result-actions"><button class="primary-action" data-takeout-action="confirm" type="button">'+(takeoutState.confirmedId===item.id?"已记入最近点过":"就点这家")+'</button><button class="dark-action" data-takeout-action="again" type="button">换一家</button><button data-takeout-action="session" type="button">本轮排除</button><button data-takeout-action="same" type="button">同类换一家</button><button data-takeout-action="different" type="button">换个类型</button><button data-takeout-action="favorite" type="button">'+(takeoutPersonal.favorites.includes(item.id)?"★ 取消收藏":"☆ 收藏")+'</button><button data-takeout-action="permanent" type="button">永久排除</button><button data-takeout-action="copy-name" type="button">复制店名</button><button data-takeout-action="copy-address" type="button">复制店名和地址</button>'+(item.evidence.sourceUrl?'<a href="'+escapeHtml(item.evidence.sourceUrl)+'" target="_blank" rel="noreferrer">查看公开来源</a>':'')+'</div></div></article>';}
      byId("takeoutBrowseResult").innerHTML=takeoutState.mode==="browse"?html:"";byId("takeoutWheelResult").innerHTML=takeoutState.mode==="wheel"?html:"";
    }
    function takeoutRenderMode(){document.querySelectorAll("[data-takeout-mode]").forEach(function(button){button.classList.toggle("active",button.dataset.takeoutMode===takeoutState.mode);});byId("takeoutBrowseMode").classList.toggle("hidden",takeoutState.mode!=="browse");byId("takeoutWheelMode").classList.toggle("hidden",takeoutState.mode!=="wheel");byId("takeoutSortWrap").style.display=takeoutState.mode==="browse"?"block":"none";takeoutRenderResult();if(takeoutState.mode==="wheel")setTimeout(takeoutDrawWheel,0);}
    function takeoutRender(){takeoutRenderFilters();takeoutRenderBrowse();var pool=takeoutState.mode==="wheel"?takeoutWheelPool():takeoutFilter();byId("takeoutCandidateCount").textContent=pool.length;byId("takeoutCategoryCount").textContent=new Set(pool.map(function(item){return item.categoryId;})).size;takeoutRenderMode();takeoutRenderManager();}
    function takeoutReset(){takeoutState.filters=Object.assign({},takeoutDefaultFilters,{categoryIds:[],distanceBandIds:[],areaIds:[],evidenceLevels:["A","B"]});takeoutState.selectedId=null;takeoutState.visible=24;byId("takeoutSearch").value="";byId("takeoutSort").value="source";takeoutRender();}
    function takeoutCopy(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text).catch(function(){});var area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();}
    function takeoutResultAction(action){var item=takeoutSelected();if(!item)return;var pool=takeoutWheelPool();if(action==="confirm"&&takeoutState.confirmedId!==item.id){takeoutPersonal.history.unshift({merchantId:item.id,merchantName:item.name,categoryId:item.categoryId,selectedAt:new Date().toISOString(),source:item.source==="custom"?"custom":"builtin"});takeoutPersonal.history=takeoutPersonal.history.slice(0,50);takeoutState.confirmedId=item.id;}else if(action==="again")takeoutSpin();else if(action==="session"){takeoutPersonal.sessionExclusions=Array.from(new Set(takeoutPersonal.sessionExclusions.concat(item.id)));takeoutState.selectedId=null;}else if(action==="same"){var same=pool.filter(function(other){return other.categoryId===item.categoryId&&other.id!==item.id;});if(same.length)takeoutState.selectedId=same[Math.floor(Math.random()*same.length)].id;}else if(action==="different"){var different=pool.filter(function(other){return other.categoryId!==item.categoryId;});var next=takeoutBalancedPick(different);if(next)takeoutState.selectedId=next.id;}else if(action==="favorite")takeoutPersonal.favorites=takeoutToggle(takeoutPersonal.favorites,item.id);else if(action==="permanent"){takeoutPersonal.permanentExclusions=Array.from(new Set(takeoutPersonal.permanentExclusions.concat(item.id)));takeoutState.selectedId=null;}else if(action==="copy-name")takeoutCopy(item.name);else if(action==="copy-address")takeoutCopy([item.name,item.address].filter(Boolean).join(" "));takeoutSave();takeoutRender();}
    function takeoutManagerMessage(message){byId("takeoutManagerMessage").textContent=message;byId("takeoutManagerMessage").style.display=message?"block":"none";}
    function takeoutList(items,action,label){return items.map(function(item){return '<article><div><h3>'+escapeHtml(item.name)+'</h3><p>'+escapeHtml(item.location?item.location.distanceDisplay:"")+'</p></div><button data-takeout-manager-action="'+action+'" data-takeout-id="'+escapeHtml(item.id)+'" type="button">'+label+'</button></article>';}).join("")||'<p class="empty">暂无记录</p>';}
    function takeoutRenderManager(){var all=takeoutAll();byId("takeoutCustomList").innerHTML=takeoutPersonal.customMerchants.map(function(item){return '<article><div><h3>'+escapeHtml(item.name)+'</h3><p>'+escapeHtml((takeoutAreaById[item.areaId]||{}).name||"")+' · '+escapeHtml(item.location.distanceDisplay)+'</p></div><div><button data-takeout-manager-action="edit" data-takeout-id="'+item.id+'" type="button">编辑</button> <button data-takeout-manager-action="delete" data-takeout-id="'+item.id+'" type="button">删除</button></div></article>';}).join("")||'<p class="empty">还没有自定义商户</p>';byId("takeoutFavoriteList").innerHTML=takeoutList(takeoutPersonal.favorites.map(function(id){return all.find(function(item){return item.id===id;});}).filter(Boolean),"unfavorite","取消收藏");byId("takeoutExcludedList").innerHTML=takeoutList(takeoutPersonal.permanentExclusions.map(function(id){return all.find(function(item){return item.id===id;});}).filter(Boolean),"restore","恢复");byId("takeoutHistoryList").innerHTML=takeoutPersonal.history.map(function(entry){return '<article><div><h3>'+escapeHtml(entry.merchantName)+'</h3><p>'+escapeHtml(new Date(entry.selectedAt).toLocaleString("zh-CN"))+'</p></div></article>';}).join("")||'<p class="empty">还没有最近点过的记录</p>';if(byId("offlineTakeoutPersonalStats"))byId("offlineTakeoutPersonalStats").textContent="个人数据："+takeoutPersonal.customMerchants.length+" 家自定义、"+takeoutPersonal.favorites.length+" 项收藏、"+takeoutPersonal.permanentExclusions.length+" 项永久排除、"+takeoutPersonal.history.length+" 条最近记录。";}
    function takeoutEditCustom(id){var item=takeoutPersonal.customMerchants.find(function(merchant){return merchant.id===id;});if(!item)return;byId("takeoutEditId").value=item.id;byId("takeoutCustomName").value=item.name;byId("takeoutCustomCategory").value=item.categoryId;byId("takeoutCustomArea").value=item.areaId;byId("takeoutCustomAddress").value=item.address||"";byId("takeoutCustomDistance").value=item.location.distanceFromPkuSouthGateKm==null?"":item.location.distanceFromPkuSouthGateKm;}
    function takeoutClearForm(){byId("takeoutCustomForm").reset();byId("takeoutEditId").value="";}
    function takeoutSaveCustom(event){event.preventDefault();var id=byId("takeoutEditId").value||"custom-takeout-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);var old=takeoutPersonal.customMerchants.find(function(item){return item.id===id;});var name=byId("takeoutCustomName").value.trim();var categoryId=byId("takeoutCustomCategory").value;var areaId=byId("takeoutCustomArea").value;var address=byId("takeoutCustomAddress").value.trim();var raw=byId("takeoutCustomDistance").value;var distance=raw===""?null:Number(raw);var band=distance==null?"":distance<1?"near_gate":distance<2?"km_1_2":distance<3?"km_2_3":"km_3_5";var item={id:id,name:name,aliases:[],searchText:[name,categoryId,areaId,address].join(" "),categoryId:categoryId,detailCategory:"自定义商户",areaId:areaId,place:null,address:address||null,location:{referenceLatitude:null,referenceLongitude:null,distanceFromPkuSouthGateKm:distance,distanceBandId:band,distanceDisplay:distance==null?"距离未填写":distance<.05?"南门附近":"约 "+distance.toFixed(1)+" km",precisionLabel:distance==null?"用户未填写":"用户填写",isEstimated:distance!=null},publicReference:{averageSpendCny:null,openingHoursText:null},delivery:{status:"unverified",statusLabel:"配送待平台确认",targetAddress:"北京大学南门",meituanVerified:false,elemeVerified:false,lastVerifiedAt:null},evidence:{level:"B",status:"user_custom",sourceDate:new Date().toISOString().slice(0,10),sourceUrl:null,note:"用户自定义"},sourceBatch:"用户自定义",enabled:true,wheelEligible:true,source:"custom",createdAt:old?old.createdAt:new Date().toISOString()};takeoutPersonal.customMerchants=old?takeoutPersonal.customMerchants.map(function(merchant){return merchant.id===id?item:merchant;}):[item].concat(takeoutPersonal.customMerchants);takeoutClearForm();takeoutManagerMessage(old?"已更新自定义商户。":"已添加自定义商户。");takeoutSave();takeoutRender();}
    function takeoutManagerAction(action,id){if(action==="edit")takeoutEditCustom(id);else if(action==="delete"){takeoutPersonal.customMerchants=takeoutPersonal.customMerchants.filter(function(item){return item.id!==id;});takeoutPersonal.favorites=takeoutPersonal.favorites.filter(function(item){return item!==id;});takeoutPersonal.permanentExclusions=takeoutPersonal.permanentExclusions.filter(function(item){return item!==id;});}else if(action==="unfavorite")takeoutPersonal.favorites=takeoutPersonal.favorites.filter(function(item){return item!==id;});else if(action==="restore")takeoutPersonal.permanentExclusions=takeoutPersonal.permanentExclusions.filter(function(item){return item!==id;});takeoutSave();takeoutRender();}
    function takeoutExport(){var payload={schemaVersion:1,exportedAt:new Date().toISOString(),customMerchants:takeoutPersonal.customMerchants,favorites:takeoutPersonal.favorites,permanentExclusions:takeoutPersonal.permanentExclusions,history:takeoutPersonal.history,settings:takeoutPersonal.settings};var url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));var link=document.createElement("a");link.href=url;link.download="食物罗盘-外卖个人数据-"+new Date().toISOString().slice(0,10)+".json";link.click();URL.revokeObjectURL(url);}
    function takeoutImportFile(event){var file=event.target.files[0];if(!file)return;file.text().then(function(text){var data=JSON.parse(text);if(data.schemaVersion!==1||!Array.isArray(data.customMerchants))throw new Error("仅支持 schemaVersion 为 1 的外卖个人数据。");var mode=document.querySelector('[name="takeoutImportMode"]:checked').value;if(mode==="replace")takeoutPersonal={customMerchants:data.customMerchants||[],favorites:data.favorites||[],permanentExclusions:data.permanentExclusions||[],history:(data.history||[]).slice(0,50),settings:data.settings||{avoidRecent:true},sessionExclusions:[]};else{var known=new Set(takeoutPersonal.customMerchants.map(function(item){return item.id;}));(data.customMerchants||[]).forEach(function(item){if(!known.has(item.id)){takeoutPersonal.customMerchants.push(item);known.add(item.id);}});takeoutPersonal.favorites=Array.from(new Set(takeoutPersonal.favorites.concat(data.favorites||[])));takeoutPersonal.permanentExclusions=Array.from(new Set(takeoutPersonal.permanentExclusions.concat(data.permanentExclusions||[])));takeoutPersonal.history=takeoutPersonal.history.concat(data.history||[]).sort(function(a,b){return b.selectedAt.localeCompare(a.selectedAt);}).slice(0,50);takeoutPersonal.settings=data.settings||takeoutPersonal.settings;}takeoutSave();takeoutRender();takeoutManagerMessage("个人数据已导入。");}).catch(function(error){takeoutManagerMessage(error.message||"导入失败。");});event.target.value="";}

    byId("takeoutCustomCategory").innerHTML=takeoutRefs.categories.map(function(item){return '<option value="'+item.id+'">'+escapeHtml(item.name)+'</option>';}).join("");byId("takeoutCustomArea").innerHTML=takeoutRefs.areas.map(function(item){return '<option value="'+item.id+'">'+escapeHtml(item.name)+'</option>';}).join("");
    byId("takeoutModeSwitch").addEventListener("click",function(event){var button=event.target.closest("[data-takeout-mode]");if(!button)return;takeoutState.mode=button.dataset.takeoutMode;takeoutRender();});
    byId("takeoutSearch").addEventListener("input",function(event){takeoutState.filters.query=event.target.value;takeoutState.visible=24;takeoutRender();});
    byId("takeoutSort").addEventListener("change",function(event){takeoutState.filters.sort=event.target.value;takeoutRender();});
    [["takeoutCategories","takeoutCategory","categoryIds"],["takeoutDistances","takeoutDistance","distanceBandIds"],["takeoutAreas","takeoutArea","areaIds"],["takeoutEvidence","takeoutEvidence","evidenceLevels"]].forEach(function(config){byId(config[0]).addEventListener("click",function(event){var button=event.target.closest("[data-"+config[1].replace(/[A-Z]/g,function(letter){return "-"+letter.toLowerCase();})+"]");if(!button)return;takeoutState.filters[config[2]]=takeoutToggle(takeoutState.filters[config[2]],button.dataset[config[1]]);takeoutState.selectedId=null;takeoutRender();});});
    byId("takeoutPresets").addEventListener("click",function(event){var button=event.target.closest("[data-takeout-preset]");if(!button)return;var preset=takeoutPresets.find(function(item){return item.id===button.dataset.takeoutPreset;});var active=takeoutPresetActive(preset);takeoutState.filters=Object.assign({},takeoutDefaultFilters,{categoryIds:[],distanceBandIds:[],areaIds:[],evidenceLevels:["A","B"]},active?{}:preset.filters);takeoutState.selectedId=null;takeoutRender();});
    byId("takeoutOnlyFavorites").addEventListener("change",function(event){takeoutState.filters.onlyFavorites=event.target.checked;takeoutRender();});byId("takeoutExcludeEstimated").addEventListener("change",function(event){takeoutState.filters.excludeEstimatedDistance=event.target.checked;takeoutRender();});byId("takeoutAvoidRecent").addEventListener("change",function(event){takeoutPersonal.settings.avoidRecent=event.target.checked;takeoutSave();takeoutRender();});
    byId("takeoutReset").addEventListener("click",takeoutReset);byId("takeoutRestoreSession").addEventListener("click",function(){takeoutPersonal.sessionExclusions=[];takeoutSave();takeoutRender();});byId("takeoutLoadMore").addEventListener("click",function(){takeoutState.visible+=24;takeoutRenderBrowse();});byId("takeoutSpin").addEventListener("click",takeoutSpin);
    byId("takeoutGrid").addEventListener("click",function(event){var button=event.target.closest("[data-takeout-merchant]");if(!button)return;takeoutState.selectedId=button.dataset.takeoutMerchant;takeoutState.confirmedId=null;takeoutRenderResult();});document.querySelectorAll("#takeoutBrowseResult,#takeoutWheelResult").forEach(function(slot){slot.addEventListener("click",function(event){var button=event.target.closest("[data-takeout-action]");if(button)takeoutResultAction(button.dataset.takeoutAction);});});
    byId("takeoutManagerOpen").addEventListener("click",function(){byId("takeoutManager").classList.add("open");});byId("takeoutManagerClose").addEventListener("click",function(){byId("takeoutManager").classList.remove("open");});byId("takeoutManagerTabs").addEventListener("click",function(event){var button=event.target.closest("[data-takeout-tab]");if(!button)return;document.querySelectorAll("[data-takeout-tab]").forEach(function(item){item.classList.toggle("active",item===button);});document.querySelectorAll("[data-takeout-panel]").forEach(function(panel){panel.classList.toggle("active",panel.dataset.takeoutPanel===button.dataset.takeoutTab);});});document.querySelectorAll(".takeout-list").forEach(function(list){list.addEventListener("click",function(event){var button=event.target.closest("[data-takeout-manager-action]");if(button)takeoutManagerAction(button.dataset.takeoutManagerAction,button.dataset.takeoutId);});});
    byId("takeoutCustomForm").addEventListener("submit",takeoutSaveCustom);byId("takeoutCancelEdit").addEventListener("click",takeoutClearForm);byId("takeoutClearHistory").addEventListener("click",function(){takeoutPersonal.history=[];takeoutSave();takeoutRender();});byId("takeoutExport").addEventListener("click",takeoutExport);byId("takeoutImport").addEventListener("change",takeoutImportFile);window.addEventListener("hashchange",function(){if(location.hash==="#takeout")setTimeout(takeoutDrawWheel,0);});
    takeoutLoad();takeoutRender();
